name: Build Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker images by Docker compose
      run: docker-compose -f docker-compose.yml -f docker-compose.override.yml build

    - name: Push Docker images by Docker compose
      run: docker-compose push ${{ secrets.DOCKERHUB_USERNAME }}/asp-api-test:dev
